#ifndef CERTS_AVAILABLE
#define CERTS_AVAILABLE

const char* CLIENT_CERT = "-----BEGIN CERTIFICATE-----\n"
"MIIDRTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"..."
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXH8AA=="

"-----END CERTIFICATE-----";

const char* CLIENT_KEY = "-----BEGIN RSA PRIVATE KEY-----"
"MIIEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"..."
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5QSAxy"
"-----END RSA PRIVATE KEY-----";

const char* CA_CERT = "-----BEGIN CERTIFICATE-----"
"MIIDRTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"..."
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5QSA=="
"-----END CERTIFICATE-----";

#endif
